### ISSUE TITLE
Path escape for query-builder

### ISSUE THREAD

**Issue by wachterjohannes** [jackalope/jackalope-jackrabbit#134]
We have a quite strange problem currently in sulu. You can create a node in jackrabbit named `test-10e` but you cannot query this path with a `ISCHILDNODE` constraint because jackrabbit says that its not "valid".

The query:

```
SELECT node.[jcr:uuid] AS uuid FROM [nt:unstructured] AS node WHERE ISCHILDNODE(node, [/cmf/candulor/contents/news/test-10e])
```

The error:

```
message: "HTTP 400: Query: SELECT node.[jcr:uuid] AS uuid FROM [nt:unstructured] AS node WHERE ISCHILDNODE(node, [/cmf/candulor/contents/news/test-(*)10e])
```

If you rename the node to `test-e` it works without any problems.

@dbu @lsmith77 do you know something like that?

As an addition: in doctrine-dbal everything works. When we escape the pathes with `"` it works in jackrabbit but not in doctrine-dbal.

**Comment by wachterjohannes** [comment]
you can take a look how i tried to escape the paths in https://github.com/sulu/sulu/pull/2387

**Comment by lsmith77** [comment]
> On 12 May 2016, at 12:04, Johannes Wachter <notifications@github.com> wrote:
> 
> We have a quite strange problem currently in sulu. You can create a node in jackrabbit named test-10e but you cannot query this path with a ISCHILDNODE constraint because jackrabbit says that its not "valid".
> 
> The query:
> 
> SELECT node.[jcr:uuid] AS uuid FROM [nt:unstructured] AS node WHERE ISCHILDNODE(node, [/cmf/candulor/contents/news/test-10e])
> The error:
> 
> message: "HTTP 400: Query: SELECT node.[jcr:uuid] AS uuid FROM [nt:unstructured] AS node WHERE ISCHILDNODE(node, [/cmf/candulor/contents/news/test-(*)10e])
> If you rename the node to test-e it works without any problems.
> 
> @dbu <https://github.com/dbu> @lsmith77 <https://github.com/lsmith77> do you know something like that?
> 
> As an addition: in doctrine-dbal everything works. When we escape the pathes with " it works in jackrabbit but not in doctrine-dbal.
> 
did you try this directly inside Jackrabbit, ie not going through our client?

**Comment by wachterjohannes** [comment]
i have tried it in the phpcr-shell. Also i have tried to execute the query inside the jackrabbit-shell (included in the jar file) - but there I have not been able to do it (:

**Comment by dbu** [comment]
this is a "known" bug: https://github.com/jackalope/jackalope/issues/313 - i investigated and it looks a lot like a bug in jackrabbit (probably the jackrabbit-remoting part)

**Comment by wachterjohannes** [comment]
@dbu thanks for the hint. i think we have to avoid this values in the node-names then.

**Comment by dbu** [comment]
i fear so - unless you want to dig into the java code. the other issue
lists the weird pattern i found that trigger the bug - its specifically
the letter "e" that seems to be a problem :-/

**Comment by wachterjohannes** [comment]
i have fixed this bug in sulu with https://github.com/sulu/sulu-document-manager/pull/91 @dbu should i close this issue?

**Comment by dbu** [comment]
lets close this and keep https://github.com/jackalope/jackalope/issues/313 open.

i created an issue on jackrabbit jira, maybe this gets fixed.

**Comment by wachterjohannes** [comment]
@dbu thanks
