### ISSUE TITLE
LogicException: Tried to start a request on a closed transport.

### ISSUE THREAD

**Issue by billsworld** [jackalope/jackalope-jackrabbit#135]
I am getting this error after updating to Symfony 3 but really not sure what is happening, here is my stack trace:

```/var/www/current/vendor/jackalope/jackalope-jackrabbit/src/Jackalope/Transport/Jackrabbit/Client.php:322
/var/www/current/vendor/jackalope/jackalope-jackrabbit/src/Jackalope/Transport/Jackrabbit/Client.php:286
/var/www/current/vendor/jackalope/jackalope-jackrabbit/src/Jackalope/Transport/Jackrabbit/Client.php:494
/var/www/current/vendor/jackalope/jackalope/src/Jackalope/ObjectManager.php:201
/var/www/current/vendor/jackalope/jackalope/src/Jackalope/Session.php:273
/var/www/current/vendor/jackalope/jackalope/src/Jackalope/Session.php:204
/var/www/current/vendor/phpcr/phpcr-utils/src/PHPCR/Util/NodeHelper.php:72
/var/www/current/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Purger/PHPCRPurger.php:75
/var/www/current/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Executor/AbstractExecutor.php:136
/var/www/current/vendor/doctrine/phpcr-bundle/DataFixtures/PHPCRExecutor.php:54
/var/www/current/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Executor/PHPCRExecutor.php:65
/var/www/current/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Executor/PHPCRExecutor.php:76
/var/www/current/vendor/symfony-cmf/testing/src/Functional/DbManager/PHPCR.php:89
```

using these packages:

        "symfony/symfony": "~3",
        "doctrine/migrations": "~1",
        "doctrine/doctrine-migrations-bundle": "~1",
        "doctrine/phpcr-bundle": "1.3.*",
        "doctrine/phpcr-odm": "1.3.*",

        "jackalope/jackalope-jackrabbit": "~1",

        "sonata-project/admin-bundle": "~3",
        "sonata-project/doctrine-extensions": "~1",
        "sonata-project/doctrine-phpcr-admin-bundle": "dev-master",
        "sonata-project/doctrine-orm-admin-bundle": "~3"

**Comment by dbu** [comment]
hm. well the exception tells you that "something" told jackrabbit to
close the connection. but i don't see from the trace why that would be.
seems it happens during loading fixtures. the cmf sandbox works with
symfony 3, so its not a fundamental problem that always happens. also,
jackrabbit itself does not use much of symfony.

can you try limiting the moving parts? like does this happen when you
only upgrade jackalope + phpcr but nothing else? does it only happen
with some test cases or also in other places? what if you run only that
test in isolation?

**Comment by billsworld** [comment]
thanks @dbu for getting back.

It seems to be strictly the upgrade from symfony ~2 to symfony ~3. As soon as I run composer with the following output the error occurs.

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing symfony/polyfill-apcu (v1.2.0)
  - Removing symfony/polyfill-php54 (v1.2.0)
  - Removing symfony/polyfill-php55 (v1.2.0)
  - Removing ircmaxell/password-compat (v1.0.4)
  - Removing symfony/symfony (v2.8.7)
  - Removing symfony/security-guard (v3.0.7)
  - Installing symfony/symfony (v3.1.1)
    Loading from cache

  - Installing psr/cache (1.0.0)
    Loading from cache

Writing lock file
Generating autoload files
```

**Comment by dbu** [comment]
can you try to reproduce the problem in a PR against the symfony-cmf sandbox?

**Comment by billsworld** [comment]
It is happening during loading fixtures, it would be the equivalent of this https://github.com/symfony-cmf/cmf-sandbox/blob/8a046db0d991a6303a52337a993afec439755b60/app/tests/WebTestCase.php#L25

I have not determined how to actually reproduce it yet however 👎

**Comment by billsworld** [comment]
This issue is related to the way in which I was loading fixtures. We need to revisit our setup code that looks like this 

```
        $em = $this->getContainer()->get('doctrine')->getManager();
        if (!isset($metadatas)) {
            $metadatas = $em->getMetadataFactory()->getAllMetadata();
        }

        $schemaTool = new SchemaTool($em);
        $schemaTool->dropDatabase();
        if (!empty($metadatas)) {
            $schemaTool->createSchema($metadatas);
        }

        $this->runCommand('doctrine:phpcr:repository:init');

        $this->db('PHPCR')->loadFixtures([
            'AppBundle\DataFixtures\PHPCR\TestData'
        ]);
```

I think the ```runCommand``` is really bad, but the other portion above that does not look the best either. Will try to provide more information.

**Comment by dbu** [comment]
afaik the recommended workflow is to have your tests start with a fresh repository and run the init in your test running script. and locally run the init manually / in the vagrant/docker setup.
