### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by steffenbrem** [jackalope/jackalope-jackrabbit#136]
I am seeing very slow query times when using Jackrabbit as the back-end for my PHPCR driven content site. Rendering a single block triggers 9 queries which take 4-5ms each, resulting in a total of 50ms. If I would fill my site with menu's, content and other blocks, it reaches 300ms! Is there any way I can improve this without moving away from PHPCR?

I am running Jackrabbit 1.12.2 standalone on a SSD drive, using the default `repository.xml`.

**Comment by dbu** [comment]
reducing the time to talk to jackrabbit below 4-5ms is probably not possible. so the focus has to be on reducing the requests.

you can try to work with the prefetch feature: https://github.com/jackalope/jackalope-jackrabbit#performance-tweaks if the nodes you use are in the same subtree. another thing could be to use findMany over find if you can, to fetch several items in one go.

you can also check with the symfony debug toolbar (assuming you use symfony) what documents are fetched. if you have ideas how to improve parts of the cmf, lets discuss in the relevant bundle. if your page is single language and has just one menu, the approach used in SimpleCmsBundle with documents that are route, menu and content all in one can only reduce the number of phpcr access needed.
