### ISSUE TITLE
Response says forbidden on Jackrabbit >= 2.12.4

### ISSUE THREAD

**Issue by danrot** [jackalope/jackalope-jackrabbit#138]
We are currently having the following issue in Sulu: https://github.com/sulu/sulu-standard/issues/756

Just for reference I am showing the error also in this Issue:

```
[PHPCR\RepositoryException]
          Unexpected error:
          CURL Error:
          Response (HTTP 403): POST
          --uri: --
          array (
            0 => 'http://localhost:8080/server/default/jcr:root/',
          )
          --curl getinfo: --
          array (
            'url' => 'http://localhost:8080/server/default/jcr:root/',
            'content_type' => 'text/html; charset=iso-8859-1',
            'http_code' => 403,
            'header_size' => 165,
            'request_size' => 7846,
            'filetime' => -1,
            'ssl_verify_result' => 0,
            'redirect_count' => 0,
            'total_time' => 0.002591,
            'namelookup_time' => 1.7E-5,
            'connect_time' => 0.000165,
            'pretransfer_time' => 0.000192,
            'size_upload' => 7588.0,
            'size_download' => 1389.0,
            'speed_download' => 536086.0,
            'speed_upload' => 2928598.0,
            'download_content_length' => 1389.0,
            'upload_content_length' => 7588.0,
            'starttransfer_time' => 0.0025690000000000001,
            'redirect_time' => 0.0,
            'redirect_url' => '',
            'primary_ip' => '::1',
            'certinfo' =>
            array (
            ),
            'primary_port' => 8080,
            'local_ip' => '::1',
            'local_port' => 64122,
          )
          --request body (size: 7588 bytes): --
          --07d542fbc64b7d5ee6f9362454e670f5
          Content-Disposition: form-data; name="/cmf/sulu_io/contents/i18n:en-created"
          Content-Type: jcr-value/date; charset=UTF-8
          Content-Transfer-Encoding: 8bit
          2016-11-16T10:10:21.000+00:00
          --07d542fbc64b7d5ee6f9362454e670f5
          Content-Disposition: form-data; name="/cmf/sulu_io/contents/i18n:en-changed"
          Content-Type: jcr-value/date; charset=UTF-8
          Content-Transfer-Encoding: 8bit
          2016-11-16T10:10:21.000+00:00
          --07d542fbc64b7d5ee6f9362454e670f5
          Content-Disposition: form-data; name="/cmf/sulu_io/contents/i18n:en-published"
          Content-Type: jcr-value/date; charset=UTF-8
          Content-Transfer-Encoding: 8bit
          2016-11-16T10:10:21.000+00:00
          --07d542fbc64b7d5ee6f9362454e670f5
          Content-Disposition: form-data; name="/cmf/sulu_io/contents/i18n:de-seo-title"
          Content-Type: jcr-value/string; charset=UTF-8
          Content-Transfer-Encoding: 8bit
          --07d542fbc64b7d5ee6f9362454e670f5
          Content-Disposition: form-data; name="/cmf/sulu_io/contents/i18n:de-seo-description"
          Content-Type: jcr-value/string; charset=UTF-8
          Content-Transfer-Encoding: 8bit
          --07d542fbc64b7d5ee6f9362454e670f5
          Content-Disposition: form-data; name="/cmf/sulu_io/contents/i18n:de-seo-keywords"
          Content-Type: jcr-value/string; charset=UTF-8
          Content-Transfer-Encoding: 8bit
          --07d542fbc64b7d5ee6f9362454e670f5
          Content-Disposition: form-data; name="/cmf/sulu_io/contents/i18n:de-seo-canonicalUrl"
          Content-Type: jcr-value/string; charset=UTF-8
          Content-Transfer-Encoding: 8bit
          --07d542fbc64b7d5ee6f9362454e670f5
          Content-Disposition: form-data; name="/cmf/sulu_io/contents/i18n:de-seo-noIndex"
          Content-Type: jcr-value/boolean; charset=UTF-8
          Content-Transfer-Encoding: 8bit
          --07d542fbc64b7d5ee6f9362454e670f5
          Content-Disposition: form-data; name="/cmf/sulu_io/contents/i18n:de-seo-noFollow"
          Content-Type: jcr-value/boolean; charset=UTF-8
          Content-Transfer-Encoding: 8bit
          --07d542fbc64b7d5ee6f9362454e670f5
          Content-Disposition: form-data; name="/cmf/sulu_io/contents/i18n
           (truncated)
          --response body (size: 1389 bytes): --
          <html>
          <head>
          <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
          <title>Error 403 FORBIDDEN</title>
          </head>
          <body><h2>HTTP ERROR 403</h2>
          <p>Problem accessing /server/default/jcr:root/. Reason:
          <pre>    FORBIDDEN</pre></p><hr /><i><small>Powered by Jetty://</small></i><br/>

          <br/>
          <br/>
          <br/>
          <br/>
          <br/>
          <br/>
          <br/>
          <br/>
          <br/>
          <br/>
          <br/>
          <br/>
          <br/>
          <br/>
          <br/>
          <br/>
          <br/>
          <br/>
          <br/>
          </body>
          </html>
          --end response body--
```

The strange thing is that creating workspaces with `$workspace->createWorkspace` and registering node types works, but as soon as `$session->save` is called I am getting the previous error.

I have digged deeper into it, and realized that there was only one change, which fixed [this issue](https://issues.apache.org/jira/browse/JCR-4009). It's about CSRF, so the 403 could be related to that error.

Is there a token or something missing the request?

**Comment by dbu** [comment]
we noticed issues with newest jackrabbit versions - the version number sounds familiar to me... CSRF and forbidden could indeed be related. you would need to dig through the transport to see if we do anything at all about CSRF atm - i'd think we don't.

**Comment by danrot** [comment]
Do you have any resources where that would have been done? Can't find any jackrabbit documentation about that. So I don't have an idea what I should be looking at 😕

**Comment by dbu** [comment]
emailed you some stuff, but found nothing on csrf in there. but did not
really read the docs so maybe there is something with a different name.

**Comment by spitcat** [comment]
i have the same error jackrabbit 2.13.4
hope we / jackrabbit can fix this soon.

**Comment by danrot** [comment]
I just tried to find out where I have to put the CSRF token, but I have no idea... I have used wireshark to compare the requests sent from the jackrabbit client itself (`java -jar jackrabbit-standalone-2.12.5.jar --cli http://localhost:8080/server`) and the doctrine phpcr shell for a simple `ls` command.

What came to my mind is that there were different HTTP methods used (phpcr-shell used POST whereby jackrabbit client used GET), and that the one from the phpcr-shell had a content type of `application/x-www-form-urlencoded` whereby the jackrabbit client didn't set a content type at all.

Tried to only change that, and got something that looks like a correct response:
```
    {":jcr:mixinTypes":"Name","jcr:mixinTypes":["rep:AccessControllable"],":jcr:primaryType":"Name","jcr:primaryType":"rep:root","jcr:system":{},"rep:policy":{}}
```

However, I got the following error message on the phpcr-shell:

```
[Symfony\Component\Debug\Exception\ContextErrorException] Notice: Undefined property: stdClass::$nodes
```

Which might be because there are no nodes at all currently, and the shell doesn't seem to handle that. However, that didn't make other commands to work, so it's probably a harder task to fix that :-/

**Comment by dbu** [comment]
you could try to ask the jackrabbit developers what changed. the more precise you can pinpoint between which versions this starts failing, the better chance of somebody finding out why. with that information we might find out what we should do on our end.

**Comment by danrot** [comment]
I've written a mail to the users mailing list of jackrabbit, I'll update the information here as soon as I get any new information.

**Comment by reschke** [comment]
Jackrabbit's CSRF protection affects any write request that could come from an HTML form, that is method==POST and content type is any of the HTML form content types.

There is no CSRF token support in Jackrabbit. 

The simplest possible fix probably is to include a Referer header field (referencing the server itself).

**Comment by dbu** [comment]
@danrot did you have a chance to try the Referer header?

**Comment by danrot** [comment]
Not yet... I am afraid that there are some places to touch... But at least it should only be the `Client` class, right?

**Comment by dbu** [comment]
i think there are a very few methods that actually send data, look for
curl calls. the referer should be configurable, defaulting to localhost.
somebody might run jackrabbit on a different host than the web server...

**Comment by danrot** [comment]
Can't we close this issue then?

**Comment by dbu** [comment]
yep, we can \o/

**Comment by spras** [comment]
@dbu : this PR is not in the version 1.2.2 , when will be release the 1.2.3, thank's ?

**Comment by dbu** [comment]
i am about to release 1.3 but there is some regression that popped up and has to be fixed before i can release.

**Comment by dbu** [comment]
yay, 1.3.0 is now tagged!

**Comment by stopsopa** [comment]
Ok, so It's 2019 we have legacy project with jackrabbit version 2.8.0 on production and I've tried to ship it through docker for local/dev environment for further work in this project. 

I couldn't find version 2.8.0 on the server [http://apache-mirror.rbc.ru/pub/apache/jackrabbit/](http://apache-mirror.rbc.ru/pub/apache/jackrabbit/) so I've used 2.8.10 but at the end using phpcr-shell I've experienced the same error mentioned in this github therad. 

I thought that It was something with php library but at the end It turned out that after building docker image with production jar file (2.8.0) solved the problem.

To make long story short: In my case It turned out that you shouldn't assume that jackrabbit team is really testing very well their code and they definitely can introduce breaking changes with patch update according semver.

**Comment by dbu** [comment]
thanks for the report. yeah unfortunately the jackrabbit people seem to not care all that much about the http stack of jackrabbit :-( 
glad you found a solution that works for you.

**Comment by reschke** [comment]
Sorry, that is BS. 

The change for JCR-4009 was addressing a CVE - a *security issue*. I also think that we've been clear about what needs to be fixed in the client to continue working.

Also, past (and outdated) releases are still available, just *read* what the downloads page says, and you'll find them at <http://archive.apache.org/dist/jackrabbit/>.

**Comment by dbu** [comment]
sorry @reschke i did not read up on the history of this ticket. you are right, while this is breaking things, it was necessary for security reasons.

**Comment by reschke** [comment]
ack and thanks for clarifying.
