### ISSUE TITLE
Workspace import does not work with protected version properties

### ISSUE THREAD

**Issue by danrot** [jackalope/jackalope-jackrabbit#139]
I have a workspace and versioned some nodes in it. When I now export the workspace with the command `app/console doctrine:phpcr:workspace:export -p /cmf test.xml` and try to reimport it with `app/console doctrine:phpcr:workspace:import -p / test.xml` I get the following error:

```
  [PHPCR\NodeType\ConstraintViolationException]
  HTTP 409: Unable to perform operation. Node is protected.
```

My guess was that this is because of the additional version fields, and I can confirm that. I have deleted all `jcr:baseVersion`, `jcr:isCheckedOut`, `jcr:predecessors` and `jcr:versionHistory` properties from the XML, and the import was working without any troubles afterwards.

I have seen that the nodes are created via the PHPCR API. Is that a good idea? There seems to be a [ProtectedPropertyImporter](https://jackrabbit.apache.org/api/2.6/org/apache/jackrabbit/core/xml/ProtectedPropertyImporter.html), which sounds like something that might work.

**Comment by danrot** [comment]
Ah, we probably can't use the Java API 🙈

**Comment by dbu** [comment]
normally the remoting api can overwrite a lot of things that the
jcr/phpcr api would not allow. the java client has to do this operation
somehow, so there might be a way to specify this correctly.

**Comment by danrot** [comment]
@dbu So what exactly are you saying? Should the import command somehow use another mechanism than creating the nodes itself?

**Comment by dbu** [comment]
no, so far things did work. i think you can't import the jcr:system path and backup/restore version information, but you operated on the path /cms so this should not be an issue. but no idea if we ever tested importing versioned nodes.

**Comment by danrot** [comment]
Ok, I have seen that there is an `importxml` command in the jackrabbit client included in the jackrabbit-standalone edition. This one can handle the system fields I've described before, but it seems to me as if deletes all these properties when there is no corresponding version node.

However, when I try to export the xml without the `-p` flag it creates a `jcr:root` node. But I realized that this one is still missing the `jcr:system` folder. The `exportsysview` command in the jackrabbit client also exports the `jcr:system` folder when choosing `/` as the src path and also includes the version information, but also seems to ignore the `jcr:system` node and in consequence the versioning information...

**Comment by dbu** [comment]
afaik to backup that kind of information, you have to go deeper and
backup the sql database / folder that jackrabbit uses to store data. we
configured jackrabbit to store into mysql and backup that db to also be
sure we don't run into size constraints with xml dumps and restores
