### ISSUE TITLE
Can't query user defined date properties

### ISSUE THREAD

**Issue by middlebrain** [jackalope/jackalope-jackrabbit#143]
Start phpcr shell and send the following commands:
````
PHPCRSH > touch dateProp 2017-02-01 --type=Date
PHPCRSH > save
PHPCRSH > q "SELECT dateProp FROM rep:root" -l sql
[PHPCR\RepositoryException] Cannot convert a date that is not a \DateTime instance to string
````
The above exception is throwed by
`vendor/phpcr/phpcr-utils/src/PHPCR/Util/ValueConverter.php:156`

The `save` command sends the follwing request to jackrabbit:
````
POST /jackrabbit/server/default/jcr:root/ HTTP/1.1
Authorization: Basic YWRtaW46YWRtaW4=
Host: localhost:8080
Accept: */*
Depth: 0
Content-Type: multipart/form-data; 
boundary=9921e60822b4ae6af62b5476e4f6d50b
User-Agent: jackalope-php/1.0
Content-Length: 410

--9921e60822b4ae6af62b5476e4f6d50b
Content-Disposition: form-data; name="/dateProp"
Content-Type: jcr-value/date; charset=UTF-8
Content-Transfer-Encoding: 8bit

2017-02-01T00:00:00.000+02:00
--9921e60822b4ae6af62b5476e4f6d50b
Content-Disposition: form-data; name=":diff"
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

^/dateProp :.
--9921e60822b4ae6af62b5476e4f6d50b--

HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
Content-Length: 0
Date: Mon, 06 Feb 2017 07:39:36 GMT
````
This looks correct to me.

And here the relevant part of the response from jackrabbit as anwer to the sql query:
```xml
...
  <dcr:column>
    <dcr:name>dateProp</dcr:name>
    <dcr:value dcr:type="String">2017-02-01T00:00:00.000+02:00</dcr:value>
  </dcr:column>
...
```
IMHO, the `dcr:type` should be `"Date"`, not `"String"`. That's the reason for the  throwed Exception.

Tested with jackrabbit 2.10.1 and 2.14.0.

The question is: Who's to blame? Jackrabbit or PHPCR / Jackalope? Or do I miss something?

**Comment by dbu** [comment]
that indeed looks wrong. i am surprised why you get the exception you see. when jackrabbit returns the data as string, i would expect jackalope to not try to cast it from date to string - how would it even know its supposed to be a date? does that only happen within the same session, or also when you leave the shell and come back?

looking at the request to jackrabbit, this seems not to specify that the value is a date. can you try to do the same with php code instead of the shell? `$session->getRootNode()->setProperty('dateProp', new \DateTime()); $session->save();` and check what that does?

note that the behaviour could be different if the property already exists, so maybe delete it between test runs.

**Comment by middlebrain** [comment]
> that indeed looks wrong. i am surprised why you get the exception you see. 

Do this mean, you can not provoke my problem on your jackrabbit/jackalope environment? No exception throwed? If yes, then the reason for the exception must be somewhere on my enviroment.

> when jackrabbit returns the data as string, i would expect jackalope to not try to cast it from date to string - how would it even know its supposed to be 
a date?

Yes, that's the crucial question. I have tried to answer this question. If I interpret the exception stack trace
````
StringPHP Fatal error:  Uncaught exception 'PHPCR\RepositoryException' with message 'Cannot convert a date that is not a \DateTime instance to string' in vendor/phpcr/phpcr-utils/src/PHPCR/Util/ValueConverter.php:159
Stack trace:
#0 vendor/jackalope/jackalope-jackrabbit/src/Jackalope/Transport/Jackrabbit/Client.php(1029): PHPCR\Util\ValueConverter->convertType('2017-07-01T00:0...', 1)
#1 vendor/jackalope/jackalope-jackrabbit/src/Jackalope/Transport/Jackrabbit/Client.php(969): Jackalope\Transport\Jackrabbit\Client->getDcrValue(Object(DOMElement))
#2 vendor/jackalope/jackalope/src/Jackalope/Query/Query.php(101): Jackalope\Transport\Jackrabbit\Client->query(Object(Jackalope\Query\Sql1Query))
#3 test.php(46): Jackalope\Query\Query->execute()
#4 test.php(24): Test->getQueryResult('sql', 'SELECT dateProp...')
#5 vendor/phpcr/phpcr-utils/src/PHPCR/Util/ValueConverter.php on line 159
````
correct, then I would say, that jackalope calls (see `vendor/phpcr/phpcr-utils/src/PHPCR/Util/ValueConverter.php:131`) the function `vendor/phpcr/phpcr/src/PHPCR/PropertyType::determineType` (line 342) which recognizes the type `String` from the jackrabbit response based on the property value as type `DATE`. 

The variable `$value` in `vendor/phpcr/phpcr-utils/src/PHPCR/Util/ValueConverter.php:158` hoever still contains a string, which explains the throwed exception. 

Note: The line numbers are from the master branch. The problem hoever exists in the stable branch too.

>does that only happen within the same session, or also when you leave the shell and come back?

The exception is throwed within (a fresh) shell and also by executing pure php code.

> looking at the request to jackrabbit, this seems not to specify that the value is a date. can you try to do the same with php code instead of the shell? $session->getRootNode()->setProperty('dateProp', new \DateTime()); $session->save(); and check what that does?

The same result. To me, the request is correct. See also http://social.isti.cnr.it:9000/jackrabbit-webapp-patched-2.4.3/remoting/write.jsp. The request example for a date is exactly the same as my posted jackrabbit request.

> note that the behaviour could be different if the property already exists, so maybe delete it between test runs.

Further research result: If I query a property which was explicit defined with type `DATE` (`jcr:created` for example), then jackrabbit is responding correctly with type `date` and jackalope is not throwing an exception.

Seems, that the type which jackrabbit returns ist always `String`, if the property type definition is `UNDEFINED`.

**Comment by middlebrain** [comment]
Addendum:

If I use `sql2` (`SELECT [dateProp] FROM [rep:root]`) then jackrabbit returns the expected type `Date`. By using `sql` or `xpath`, jackrabbit returns the wrong type `String`. Seems to be a bug in jackrabbit.

**Comment by dbu** [comment]
do we need to work around that bug on our side, or can we close this issue?

**Comment by middlebrain** [comment]
I think you can close this issue. Using sql2 is a sufficient workaround to me.

**Comment by dbu** [comment]
great! i think sql and xpath are considered as not important by jackrabbit, so likely they wont go and fix the bugs in those.
