### ISSUE TITLE
Bad performance quering thousands of nodes

### ISSUE THREAD

**Issue by middlebrain** [jackalope/jackalope-jackrabbit#144]
Because there is no `SELECT COUNT(*)` in jackrabbit sql/sql2 or something similar in xpath, I'm forced to use something like this: `SELECT [jcr:score] FROM [foo:bar]` and count the result.

If there are thousands of `foo:bar` nodes, the performance is terrible. Jackrabbit emits multi megabyte xml quick, but jackalope-jackrabbit is doing a bad job parsing such big xml chunks.

For testing I have created 20,000 Nodes with a snippet like that:
````php
$session = ...
$rootNode = $session->getRootNode();
$childNode = $rootNode->addNode("childnode");

for ( $i = 0; $i < 20000; $i++ ) {
  $childNode->addNode(uniqid());
}

$session->save();
````
Counting the nodes with something like that ...
````php
$session = ...
$ws = $session->getWorkspace();
$qm = $ws->getQueryManager();
$q = $qm->createQuery("SELECT [jcr:score] FROM [nt:unstructured]", "JCR-SQL2");
$total = iterator_count($q->execute());
````
... lasted about 68 seconds on my machine.

The reason for this bad performance is in file `vendor/jackalope/jackalope-jackrabbit/src/Jackalope/Transport/Jackrabbit/Client.php` line 963 (current master branch):

`foreach ($dom->getElementsByTagName('response') as $row) {`

With the following patch, the counting time decreased from about 68 seconds to 1-2 seconds.

````diff
--- Client.php<>2017-02-08 17:58:47.000000000 +0100
+++ Client.php<>2017-02-13 15:10:23.348170771 +0100
@@ -958,9 +958,10 @@
.
         $dom = new DOMDocument();
         $dom->loadXML($rawData);
+        $domXpath = new \DOMXPath($dom);
.
         $rows = array();
-        foreach ($dom->getElementsByTagName('response') as $row) {
+        foreach ($domXpath->query('D:response') as $row) {
             $columns = array();
             foreach ($row->getElementsByTagName('column') as $column) {
                 $sets = array();
````
Please note, I'm not a php xml expert. This is a random fix based on google research.

**Comment by dbu** [comment]
thanks for this detailed report and digging for a possible solution! i am no php xml expert either, but this looks reasonable. can you please do a pull request with this change? then we can see if all the tests still work - it looks like they should if your query works.

if you have massive amounts of data, be aware that jackrabbit is primarily meant as a structured data repository. if your application is very heavy on search, it might make sense to index data (possibly optimized for the searches you do) in elasticsearch / solr. doing queries should be fine in jackrabbit (it uses lucene underneath for search) but as you found the support for large result sets is lacking. huge searches might also be an indicator that the content is not organized in the way that it is used (or maybe not, just saying).

we did work on lazy loading some things, like https://github.com/jackalope/jackalope/pull/304 . maybe there is further optimization possible to not loop over 20k results in Client.php but delay to do that in batches when they are actually requested. i assume most of the time you won't actually process all the results? with xpath it should be possible to get the count cheaper i'd hope. i did not look into this however, so no idea how feasable it is, while respecting the PHPCR interfaces.

**Comment by middlebrain** [comment]
In our small cms system we need pagination all over the place. For example in site view for articles (mostly 10 at once) or in the backend view for newsletter subscribers (50 at once).

For rendering the navigation view, the total number of articles, subscribers, ...) is needed. I did not expect, that getting a simple number was (a lot) slower then getting a (small) subset of the articles, subscribers, events or whatever.

It is unlikely that we reach 20k child nodes sometimes. It was an show case example only.

**Comment by dbu** [comment]
does #145 fix this issue or do you think something else is needed?

**Comment by middlebrain** [comment]
May be, if this fix is not sufficient someday, I will try this:

http://mail-archives.apache.org/mod_mbox/jackrabbit-dev/201203.mbox/%3C4F76A1D0.2050901%40liip.ch%3E

Thanks for merging.
