### ISSUE TITLE
Not longer working with jackalope 1.3.6

### ISSUE THREAD

**Issue by alexander-schranz** [jackalope/jackalope-jackrabbit#156]
The changes in https://github.com/jackalope/jackalope/pull/351

seems to crash the sql2 query operations with aliases?

The following test is failing currently

```
1) PHPCR\Tests\Query\QuerySql2OperationsTest::testQueryFieldDate
PHPCR\RepositoryException: Attempting to get the path for a non existent selector: nt:unstructured

/private/tmp/jackalope-jackrabbit/vendor/jackalope/jackalope/src/Jackalope/Query/Row.php:208
/private/tmp/jackalope-jackrabbit/vendor/phpcr/phpcr-api-tests/tests/Query/QuerySql2OperationsTest.php:70

ERRORS!
Tests: 1866, Assertions: 8624, Errors: 1, Skipped: 62, Incomplete: 12.
```

Not sure whre this issue need to be fixed.

**Comment by dbu** [comment]
@alexander-schranz can you please check if https://github.com/jackalope/jackalope/pull/353 fixes that issue?

**Comment by dbu** [comment]
fixed in https://github.com/jackalope/jackalope/pull/353
