### ISSUE TITLE
"Problem (2) in the Chunked-Encoded data" while performing a CURL request

### ISSUE THREAD

**Issue by eXsio** [jackalope/jackalope-jackrabbit#89]
Hello

I've stumbled on a weird error lately. I've switched my computer to a newer model and started experiencing weird random behaviours when interacting with Jackrabbit. Sometimes (without a particular reason), when a CURL request is dispatched to my local Jackrabbit, this exception is thrown:

```
PHPCR\RepositoryException
Message: Not a valid json object: 
Request: POST http://localhost:7400/server/[repo_name]/jcr:root/.0.json 
Response: 
```

It turns out, that the response returned by CURL is a boolean(false). Tracking the latest curl_error associated with the problematic handle revealed a cryptic error msg:

```
Problem (2) in the Chunked-Encoded data
```

Don't know, if anyone else had a problem like that. It turned out, that the solution is simple. All it takes for CURL to start behaving normally is adding a new option to CURL handle:

```
$curl->setopt(CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_1_0);
```

in 

```
Jackalope\Transport\Jackrabbit\Request::singleRequest(436)
```

This option changes the HTTP version from 1.1 to 1.0. From my experience that did not break antyhing, but I can't be sure. I dont know what is causing this error - is it my NIC driver or something else... on my teammates computer everything looks fine. Any ideas? Thoughts?

**Comment by danrot** [comment]
Just FYI: We are running into this same issue again on curl 7.36, curl_error also shows the same error:

```
Problem (2) in the Chunked-Encoded data
```

For us it happens if we add a reference to one of two specific nodes. Then both sides of the references is failing with this issue. We' don't really know why it's failing exactly for these two pages.

Setting the HTTP version to 1.0 as described above works for us.

We are now trying to update to a newer curl version, and see if this works.

**Comment by danrot** [comment]
@eXsio Do you remember if this also happened if you executed a curl request from the terminal? This works for us, but in PHP we get this error... And the changelog of curl doesn't include any changes concerning chunk encoding since 7.36...

**Comment by zw8686** [comment]
Hello, I am using json_decode function, met
"Problem (2) in the Chunked - Encoded data"
And you know how to solve?

**Comment by dbu** [comment]
it seems curl 7.35 was reason for this issue in the past.
for others, the force_http_version_10 option to the jackalope-jackrabbit transport helped. did you try those two things already?

**Comment by LocutusOfBorg** [comment]
lol, happy to see people are using my ettercap backport to get an updated curl
I'll fix the trusty in an update soon :)

**Comment by jpeak5** [comment]
thanks much jackalope people! for the suggestion to upgrade cURL on Ubuntu...

**Comment by alexander-schranz** [comment]
Got the same error on Ubuntu 16.08 with Curl 7.47 when trying to import a workspace.
Tried to configure the force http10 over doctrine_phpcr bundle the following way:

```
doctrine_phpcr:
    session:
        sessions:
            default:
                backend:
                    type: jackrabbit
                    parameters:
                        jackalope.jackrabbit_force_http_version_10: true
                        jackalope.check_login_on_server: false
```

but still the same problem. Any ideas what else it could fix?
