### ISSUE TITLE
Cannot save after error saying that the node must be saved to checkin the node

### ISSUE THREAD

**Issue by dantleech** [jackalope/jackalope-jackrabbit#93]
Catch 22 situation..

````
[PHPCR\InvalidItemStateException] You may not checkin node at /cms/homepage with pending unsaved changes
PHPCRSH > save
[PHPCR\Version\VersionException] HTTP 409: Unable to perform operation. Node is checked-in.
````

**Comment by dbu** [comment]
do we want to keep the post-error bugs open? i think it will be really hard to fix the repository state after exceptions

**Comment by dbu** [comment]
so we say that with an error after `save` it is likely that the application state is invalid and you need to refresh.
