### ISSUE TITLE
Very long pause when running intensive tests

### ISSUE THREAD

**Issue by dantleech** [jackalope/jackalope-jackrabbit#96]
I have noticed that with both PHPCR Shell and the Sulu CMF that when running a large series of functional tests involving the Jackrabbit implementation, the system will lock-up at the same point for maybe 5 minutes and then resume.

The point that the system locks up depends on where the tests start, so it seems this happens after a certain number of operations and does not seem to be related to any operation in particular.

**Comment by dbu** [comment]
does this still happen? or can we close this?

**Comment by dbu** [comment]
@dantleech do we still keep this open or can we close it?
